# Generated by Django 3.2.9 on 2021-11-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0002_gif_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
